name = "employee-management-web"
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ticketing-db"
database_id = "10d0526d-b506-40be-b44d-48b7a9f789f7"
migrations_dir = "migrations"

[vars]
AUTH_SECRET = "PLACEHOLDER_SECRET"
NEXTAUTH_URL = "http://localhost:3000"
