name = "employee-management-web"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "ticketing-db"
database_id = "10d0526d-b506-40be-b44d-48b7a9f789f7"
migrations_dir = "migrations"

[vars]
NEXTAUTH_URL = "http://localhost:3000"
